### ISSUE TITLE
Schematic

### ISSUE THREAD

**Issue by jamesy0ung** [walczakp/xbox360-teensy-flasher#1]
Can we get a schematic of the Teensy LC connected to the Xbox 360? I am asking because I am going to change the pins to work on the ATMega16U2 of the Arduino Uno. The pin names in XSPI.h are not exactly clear, so I am going to work out what they are based on the schematic.

**Comment by jamesy0ung** [comment]
![image](https://user-images.githubusercontent.com/17939249/117928988-a3f53600-b33f-11eb-9281-6c7ef264da93.png)
I found this image. I should be able to make it work now.

**Comment by walczakp** [comment]
Hello, thanks for your input. I intentionally skipped the schematics due to variety of xbox motherboard versions out there. I agree it might be a good idea though, to provide the information.

BTW Please let me know how it works for Arduino, maybe we could make this project working on both Teensy and Arduino.
